-- CreateTable
CREATE TABLE "NhanVien" (
    "MaNV" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "HoTen" TEXT NOT NULL,
    "VaiTro" TEXT NOT NULL,
    "MatKhau" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "KhachHang" (
    "MaKH" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "HoTen" TEXT NOT NULL,
    "SDT" TEXT NOT NULL,
    "DiemTichLuy" INTEGER NOT NULL DEFAULT 0
);

-- CreateTable
CREATE TABLE "LoaiHang" (
    "MaLoai" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "TenLoai" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "SanPham" (
    "MaSP" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "TenSP" TEXT NOT NULL,
    "DonGiaBan" REAL NOT NULL,
    "ThueVAT" REAL NOT NULL,
    "SoLuongTon" INTEGER NOT NULL DEFAULT 0,
    "MaLoai" INTEGER NOT NULL,
    CONSTRAINT "SanPham_MaLoai_fkey" FOREIGN KEY ("MaLoai") REFERENCES "LoaiHang" ("MaLoai") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "LoHang" (
    "MaLo" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "NgayNhap" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "HanSuDung" DATETIME NOT NULL,
    "SoLuongNhap" INTEGER NOT NULL,
    "SoLuongTon" INTEGER NOT NULL,
    "MaSP" INTEGER NOT NULL,
    CONSTRAINT "LoHang_MaSP_fkey" FOREIGN KEY ("MaSP") REFERENCES "SanPham" ("MaSP") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "HoaDon" (
    "MaHD" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "NgayTao" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TongTienHang" REAL NOT NULL,
    "TongThueGTGT" REAL NOT NULL,
    "PhuongThucThanhToan" TEXT NOT NULL,
    "GiamGia" REAL NOT NULL DEFAULT 0,
    "MaNV" INTEGER NOT NULL,
    "MaKH" INTEGER,
    CONSTRAINT "HoaDon_MaNV_fkey" FOREIGN KEY ("MaNV") REFERENCES "NhanVien" ("MaNV") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "HoaDon_MaKH_fkey" FOREIGN KEY ("MaKH") REFERENCES "KhachHang" ("MaKH") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "ChiTietHoaDon" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "SoLuong" INTEGER NOT NULL,
    "DonGia" REAL NOT NULL,
    "ThanhTien" REAL NOT NULL,
    "MaHD" INTEGER NOT NULL,
    "MaSP" INTEGER NOT NULL,
    CONSTRAINT "ChiTietHoaDon_MaHD_fkey" FOREIGN KEY ("MaHD") REFERENCES "HoaDon" ("MaHD") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "ChiTietHoaDon_MaSP_fkey" FOREIGN KEY ("MaSP") REFERENCES "SanPham" ("MaSP") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "KhachHang_SDT_key" ON "KhachHang"("SDT");
